### ISSUE TITLE
Combustion fails on v2.5.0

### ISSUE THREAD

**Issue by bibendi** [palkan/anyway_config#134]
Hi Vova! We have a problem :)

After updating of anyway_config to v2.5, the Combustion fails to start.

## Additional context

```
>> BUNDLE_GEMFILE=/builds/nstmrt/rubygems/sbmt-kafka_producer/gemfiles/rails_7.0.gemfile bundle exec rspec --format RspecJunitFormatter --out test-results/rspec_3.1.xml --format documentation
Anyway Config was loaded before Rails. Activating Anyway Config Rails plugins now.
NOTE: Already loaded configs were provisioned without Rails-specific sources.
An error occurred while loading rails_helper.
Failure/Error: require "combustion"
ArgumentError:
  wrong number of arguments (given 1, expected 0)
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/railtie/configuration.rb:8:in `initialize'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:384:in `new'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:384:in `config'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails.rb:64:in `root'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/rails/settings.rb:20:in `autoload_static_config_path='
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/railtie.rb:12:in `block in <class:Railtie>'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:59:in `each'
# /usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/railtie/configuration.rb:55:in `before_configuration'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/railtie.rb:10:in `<class:Railtie>'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/railtie.rb:7:in `<module:Anyway>'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/railtie.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/rails.rb:19:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/anyway_config-2.5.0/lib/anyway/rails/autoload.rb:31:in `tracepoint_class_callback'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/engine/configuration.rb:6:in `<module:Rails>'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/engine/configuration.rb:5:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/application/configuration.rb:7:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:384:in `config'
# /usr/local/bundle/gems/railties-7.0.6/lib/rails/railtie.rb:146:in `config'
# /usr/local/bundle/gems/combustion-1.3.7/lib/combustion/application.rb:19:in `<class:Application>'
# /usr/local/bundle/gems/combustion-1.3.7/lib/combustion/application.rb:8:in `<module:Combustion>'
# /usr/local/bundle/gems/combustion-1.3.7/lib/combustion/application.rb:7:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/combustion-1.3.7/lib/combustion.rb:96:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
```

## Environment

**Ruby Version:** 3.1

**Framework Version (Rails, whatever):** 7.0

**Anyway Config Version:** 2.5

**Comment by palkan** [comment]
Hey! Push a fix to master, can you check, please?

**Comment by bibendi** [comment]
The fix has helped us. Thank you! Can you release a new version?

**Comment by palkan** [comment]
Sure! 2.5.1 is out.
